name: Test Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy on remote server
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ssh ubuntu@${{ vars.SSH_HOST }} \
          "cd /var/www/html/elite-test-pipeline \
          && git remote set-url origin git@github.com:${{ vars.REPOSITORY }}.git \
          && export NVM_DIR=~/.nvm \
          && source ~/.nvm/nvm.sh \
          && git config --global --add safe.directory /var/www/html/elite-test-pipeline \
          && git checkout main \
          && git pull \
          && npm install \
          && npm run build \
          && exit"

      - name: Cleanup
        run: rm -rf ~/.ssh
